# -*- coding: utf-8 -*-
"""sonika_deep_new_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HB-V33R0epGxqaTSASv5HE5I7v9X0n5L
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

floc='/content/drive/MyDrive/sonika_deep/'

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
import numpy as np

def final_model():
  model=[]
  model.append(MultinomialNB())
  model.append(BernoulliNB())
  model.append(GaussianNB())
  model.append(DecisionTreeClassifier())
  model.append(LogisticRegression())
  model.append(KNeighborsClassifier())
  model.append(svm.SVC(kernel="linear",probability=True))
  model.append(svm.SVC(kernel="poly",probability=True))
  model.append(svm.SVC(kernel="rbf",probability=True))
  model.append(BaggingClassifier(MultinomialNB(),max_samples=0.5, max_features=0.5))
  model.append(BaggingClassifier(DecisionTreeClassifier(),max_samples=0.5, max_features=0.5))
  model.append(BaggingClassifier(LogisticRegression(),max_samples=0.5, max_features=0.5))
  model.append(BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5))
  model.append(RandomForestClassifier(n_estimators=10))
  model.append(ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0))
  model.append(AdaBoostClassifier(n_estimators=10))
  model.append(GradientBoostingClassifier(n_estimators=10, learning_rate=1.0,max_depth=1, random_state=0))
  #model.append(MLPClassifier(solver='lbfgs', hidden_layer_sizes=(trdata.shape[1], 2), random_state=1,max_iter=1500))
  #model.append(MLPClassifier(solver='sgd', hidden_layer_sizes=(trdata.shape[1], 2), random_state=1,max_iter=1500))
  #model.append(MLPClassifier(solver='adam', hidden_layer_sizes=(trdata.shape[1], 2), random_state=1,max_iter=1500))
  return model

import numpy as np
np.random.randint(0,100,10)

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
kf=KFold(n_splits=3)
for i in range(964,980):
  fname=floc+str(i+1)+'.csv'
  print(fname)
  df=np.genfromtxt(fname,delimiter=',')
  np.random.shuffle(df)
  X=df[:,0:-1]
  y=df[:,-1]
  pred=np.zeros((np.shape(df)[0],18))
  pred1=np.zeros((np.shape(df)[0],18))
  for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model=final_model()
    j=0
    for m in model:
      m.fit(X_train,y_train)
      pred[test_index,j]=m.predict(X_test)
      pred1[test_index,j]=m.predict_proba(X_test)[:,1]
      j=j+1
    pred[test_index,17]=y_test
    pred1[test_index,17]=y_test
  fname=floc+str(i+1)+'trial_n'+'.csv'
  np.savetxt(fname,pred, delimiter=',', fmt='%f')
  fname=floc+str(i+1)+'ptrial_n'+'.csv'
  np.savetxt(fname,pred1, delimiter=',', fmt='%f')