# -*- coding: utf-8 -*-
"""sonika_deep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdRrSuFfeUQTZ56QCnRd12YMbvTslaGk
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

floc='/content/drive/MyDrive/sonika_deep/'

for i in range(0,1):
  for j in range(0,22):
    fname=floc+str(54*j+i+1)+'.csv'
    data=np.genfromtxt(fname,delimiter=',')
    print(i,j,np.shape(data))

from imblearn.over_sampling import SMOTE
def samdata(data):
  sm = SMOTE(random_state=25)
  datan=data[:,0:-1]
  out=data[:,-1]
  X_res, y_res = sm.fit_resample(datan,out)
  y=y_res.reshape(-1,1)
  d=np.concatenate((X_res,y),axis=1)
  return d

for i in range(0,54*11):
    fname=floc+str(i+1)+'.csv'
    df=np.genfromtxt(fname,delimiter=',')
    d=samdata(df)
    fname=floc+str(54*11+i+1)+'.csv'
    np.savetxt(fname,d, delimiter=',', fmt='%f')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(
    monitor='val_accuracy',
    mode='max',
    patience=10,
    restore_best_weights=True
)

def model_1_hidden(input_dim=20):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(input_dim,)),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model


# ======================================================
# Function: 2 Hidden Layers
# ======================================================
def model_2_hidden(input_dim=20):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(input_dim,)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model


# ======================================================
# Function: 3 Hidden Layers
# ======================================================
def model_3_hidden(input_dim=20):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(input_dim,)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model


# ======================================================
# Function: 4 Hidden Layers
# ======================================================
def model_4_hidden(input_dim=20):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(input_dim,)),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model


# ======================================================
# Function: 5 Hidden Layers
# ======================================================
def model_5_hidden(input_dim=20):
    model = Sequential([
        Dense(256, activation='relu', input_shape=(input_dim,)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model


# ======================================================
# Function: 6 Hidden Layers
# ======================================================
def model_6_hidden(input_dim=20):
    model = Sequential([
        Dense(256, activation='relu', input_shape=(input_dim,)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(8, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
    return model

def dnnmodel(noi):
  model=[]
  model.append(model_1_hidden(noi))
  model.append(model_2_hidden(noi))
  model.append(model_3_hidden(noi))
  model.append(model_4_hidden(noi))
  model.append(model_5_hidden(noi))
  model.append(model_6_hidden(noi))
  return model

from sklearn.metrics import confusion_matrix

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
kf=KFold(n_splits=3)
for i in range(954,957):
  fname=floc+str(i+1)+'.csv'
  print(fname)
  df=np.genfromtxt(fname,delimiter=',')
  np.random.shuffle(df)
  X=df[:,0:-1]
  y=df[:,-1]
  pred=np.zeros((np.shape(df)[0],7))
  pred1=np.zeros((np.shape(df)[0],7))
  for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model=dnnmodel(np.shape(X_train)[1])
    j=0
    for m in model:
      m.fit(X_train,y_train,epochs=50,batch_size=128,validation_split=0.2,verbose=0)
      pred[test_index,j]=(m.predict(X_test) > 0.5).astype(int).reshape(1,-1)
      pred1[test_index,j]=m.predict(X_test).reshape(1,-1)
      j=j+1
    pred[test_index,6]=y_test
    pred1[test_index,6]=y_test
  for j in range(0,6):
    print(confusion_matrix(pred[:,6],pred[:,j]))
    print(accuracy_score(pred[:,6],pred[:,j]))
  fname=floc+str(i+1)+'trial'+'.csv'
  np.savetxt(fname,pred, delimiter=',', fmt='%f')
  fname=floc+str(i+1)+'ptrial'+'.csv'
  np.savetxt(fname,pred1, delimiter=',', fmt='%f')

for i in range(0,1188):
  fname=floc+str(i+1)+'trial_n'+'.csv'
  try:
    data=np.genfromtxt(fname,delimiter=',')
  except:
    print(i,'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh')